Blood level indicator
ArmaForces/Wiki pull request #35
Opened 2021-08-01 15:43 UTC by Zaborz

Short description of blood level indicator + images

Co-Authored-By: Smieszkokoleszko <63968615+Smieszkokoleszko@users.noreply.github.com>

2021-08-01 21:36 UTC, 3Mydlo3 commented on docs/guides/medical.md
> +
This is a bit messy, consider making a table of it. Maybe like this (you can fine tune this as I made this quickly).
```suggestion

|   Krew (L)   |                             Oznaczenie                              |
| ------------ | ------------------------------------------------------------------- |
| (5,1 - 4,85) | ![Wskaźnik utraty krwi1](../_data/guides/medical/bloodVolume_1.png) |
| (4,85 - 4,6) | ![Wskaźnik utraty krwi2](../_data/guides/medical/bloodVolume_2.png) |
| (4,6 - 4,35) | ![Wskaźnik utraty krwi3](../_data/guides/medical/bloodVolume_3.png) |
| (4,1 - 3,85) | ![Wskaźnik utraty krwi4](../_data/guides/medical/bloodVolume_4.png) |
| (3,85 - 3,0) | ![Wskaźnik utraty krwi5](../_data/guides/medical/bloodVolume_5.png) |
```

2021-08-01 21:37 UTC, 3Mydlo3 requested changes
Please make the icons take less vertical space on page.

2021-08-02 11:16 UTC, Zaborz commented
New commit - Implementation of changes
Implementation of table with blood range of values and corresponding images + image showing position of blood level indicator on the screen.

2021-08-02 15:37 UTC, 3Mydlo3 approved these changes

2021-08-05 17:49 UTC, merged