Hotfix - Blood level indicator medical guide
ArmaForces/Wiki pull request #36
Opened 2021-08-05 18:39 UTC by Zaborz

Missing one row + image in the table.

2021-08-07 10:36 UTC, 3Mydlo3 requested changes
Please fix conflicts and make sure only correct changes are in `Files changed` tab as right now there are too many.

2021-08-21 18:57 UTC, Zaborz commented
Fixed conflicts of files as requested.

2021-08-21 19:31 UTC, Smieszkokoleszko approved these changes
Now looks fine for me.

2021-08-22 22:25 UTC, 3Mydlo3 approved these changes

2021-08-23 07:33 UTC, merged